# Generated by Django 6.0.2 on 2026-02-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Введите название места : например, работа. дом. пляж, улица и т.д.",
                        max_length=50,
                        verbose_name="Название локации",
                    ),
                ),
                (
                    "clarifying",
                    models.TextField(
                        help_text="Детально уточните места действия: беговая дорожка в зале, на коврике в комнате и т.д.",
                        verbose_name="Описание (уточнение) места действия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место действия",
                "verbose_name_plural": "Места действия",
            },
        ),
    ]
