# Generated by Django 6.0.2 on 2026-02-10 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="award",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Вознаграждение — чем пользователь должен себя вознаградить после выполнения.",
                max_length=50,
                verbose_name="Название вознаграждения",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="award",
            name="description",
            field=models.TextField(
                default=django.utils.timezone.now,
                help_text="Детально уточните места действия: беговая дорожка в зале, на коврике в комнате и т.д.",
                verbose_name="Описание (уточнение) места действия",
            ),
            preserve_default=False,
        ),
    ]
