# Generated by Django 6.0.2 on 2026-02-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_award_award_award_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="award",
            options={
                "ordering": ["award"],
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["location"],
                "verbose_name": "Место действия",
                "verbose_name_plural": "Места действия",
            },
        ),
    ]
