# Generated by Django 6.0.2 on 2026-02-12 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_award_options_alter_place_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["action", "place"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="action",
            field=models.CharField(
                blank=True,
                help_text="Укажите само действие - привычку",
                max_length=50,
                null=True,
                verbose_name="Действие - привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="award",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.award",
                verbose_name="Выберите вознаграждение",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Время на выполнение в секундах", null=True
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Укажите является ли действие - привычка приятной привычки",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Укажите что привычка публичная",
                verbose_name="Публичная",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Периодичность (дни)"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.place",
                verbose_name="Выберите место",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Указывается только для полезных привычек. Не может быть приятной привычкой.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pleasant_rewards",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Укажите в какое время будет осуществляться привычка",
                null=True,
                verbose_name="Время",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
